server:
  port: 8762


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: VIDEO-SERVICE
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/video/**
        - id: RECOMMENDATION-SERVICE
          uri: lb://RECOMANDATION-SERVICE
          predicates:
            - Path=/recommendation/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost