server:
  port: 9001
spring:
  application:
    name: recommendation
  datasource:
    url: jdbc:h2:mem:recommendation
  sql:
    init:
      platform: h2
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost