server:
  port: 9000

spring:
  application:
    name: VIDEO-SERVICE
  datasource:
    url: jdbc:h2:mem:video
  sql:
    init:
      platform: h2
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

recommendation:
  url: http://recommendation